version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: infratech
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: