# Generated by Django 5.2.15 on 2026-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_metric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='uptime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
